name: mobile_survey
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+10

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  http_proxy: ^1.2.1
  provider: ^6.0.4
  image_picker: ^0.8.4+1
  camera: ^0.9.2+2
  dropdown_button2: ^1.9.2
  group_radio_button: ^1.3.0
  webview_flutter: ^4.2.2
  http: ^0.13.5
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  floor: ^1.4.2
  sqflite: ^2.0.2
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  device_info_plus: ^8.2.2
  get_ip_address: ^0.0.5
  intl: ^0.18.0
  connectivity_plus: ^3.0.6
  internet_connection_checker: ^0.0.1+3
  path: ^1.7.0
  open_file: ^3.2.1
  path_provider: ^2.0.4
  pdf: ^3.8.4
  flutter_map: ^2.2.0
  latlong2: ^0.8.2
  geocoding: ^2.0.5
  url_launcher: ^6.1.10
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.2
  flutter_local_notifications: ^13.0.0
  notification_permissions: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.4.2
  build_runner: ^2.1.2
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icon/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
